CREATE TABLE IF NOT EXISTS participants (
    id CHAR(36) PRIMARY KEY,
    nim VARCHAR(31) NOT NULL,
    name VARCHAR(127) NOT NULL,
    class_id INT DEFAULT 0 REFERENCES classes(id) ON DELETE SET DEFAULT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS team_participants (
    team_id CHAR(36) NOT NULL,
    participant_id CHAR(36) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
