CREATE TABLE IF NOT EXISTS repl_courses (
    id INT NOT NULL PRIMARY KEY,
    name VARCHAR(63) NOT NULL,
    year INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO repl_courses (id, name, year)
VALUES (0, '-', 0);

CREATE TABLE IF NOT EXISTS classes (
    id SERIAL PRIMARY KEY,
    name CHAR(1) NOT NULL DEFAULT 'X',
    course_id INT DEFAULT 0 REFERENCES repl_courses(id) ON DELETE SET DEFAULT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO classes (id, name, course_id)
VALUES (0, '-', 0);

CREATE TABLE IF NOT EXISTS teams (
    id CHAR(36) PRIMARY KEY,
    number SMALLINT NOT NULL DEFAULT 0,
    class_id INT DEFAULT 0 REFERENCES classes(id) ON DELETE SET DEFAULT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);