// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: class.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteClass = `-- name: DeleteClass :exec
DELETE FROM classes
WHERE id = $1
`

func (q *Queries) DeleteClass(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteClass, id)
	return err
}

const findClassesByCourseID = `-- name: FindClassesByCourseID :many
SELECT
    c.id,
    c.name,
    c.course_id,
    rc.name AS course_name,
    rc.year AS course_year,
    c.created_at,
    c.updated_at
FROM classes c
INNER JOIN repl_courses rc ON c.course_id = rc.id
WHERE c.course_id = $1
ORDER BY c.name
`

type FindClassesByCourseIDRow struct {
	ID         int32
	Name       string
	CourseID   pgtype.Int4
	CourseName string
	CourseYear int32
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

func (q *Queries) FindClassesByCourseID(ctx context.Context, courseID pgtype.Int4) ([]FindClassesByCourseIDRow, error) {
	rows, err := q.db.Query(ctx, findClassesByCourseID, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindClassesByCourseIDRow
	for rows.Next() {
		var i FindClassesByCourseIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CourseID,
			&i.CourseName,
			&i.CourseYear,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertClass = `-- name: InsertClass :one
INSERT INTO classes (name, course_id)
VALUES ($1, $2)
RETURNING id
`

type InsertClassParams struct {
	Name     string
	CourseID pgtype.Int4
}

func (q *Queries) InsertClass(ctx context.Context, arg InsertClassParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertClass, arg.Name, arg.CourseID)
	var id int32
	err := row.Scan(&id)
	return id, err
}
