// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: course.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCourseByID = `-- name: DeleteCourseByID :exec
DELETE FROM repl_courses
WHERE id = $1
`

func (q *Queries) DeleteCourseByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCourseByID, id)
	return err
}

const insertCourse = `-- name: InsertCourse :exec
INSERT INTO repl_courses (id, name, year)
VALUES ($1, $2, $3)
`

type InsertCourseParams struct {
	ID   int32
	Name string
	Year int32
}

func (q *Queries) InsertCourse(ctx context.Context, arg InsertCourseParams) error {
	_, err := q.db.Exec(ctx, insertCourse, arg.ID, arg.Name, arg.Year)
	return err
}

const updateCourseName = `-- name: UpdateCourseName :exec
UPDATE repl_courses
SET
    name = $1,
    updated_at = $2
WHERE id = $3
`

type UpdateCourseNameParams struct {
	Name      string
	UpdatedAt pgtype.Timestamp
	ID        int32
}

func (q *Queries) UpdateCourseName(ctx context.Context, arg UpdateCourseNameParams) error {
	_, err := q.db.Exec(ctx, updateCourseName, arg.Name, arg.UpdatedAt, arg.ID)
	return err
}
