// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Class struct {
	ID        int32
	Name      string
	CourseID  pgtype.Int4
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Participant struct {
	ID        string
	Nim       string
	Name      string
	ClassID   pgtype.Int4
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type ReplCourse struct {
	ID        int32
	Name      string
	Year      int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Team struct {
	ID        string
	Number    int16
	ClassID   pgtype.Int4
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type TeamParticipant struct {
	TeamID        string
	ParticipantID string
	CreatedAt     pgtype.Timestamp
}
