// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: participant.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findParticipantByID = `-- name: FindParticipantByID :one
SELECT id, nim, name, class_id, created_at, updated_at
FROM participants
WHERE id = $1
`

func (q *Queries) FindParticipantByID(ctx context.Context, id string) (Participant, error) {
	row := q.db.QueryRow(ctx, findParticipantByID, id)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.Nim,
		&i.Name,
		&i.ClassID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findParticipantsByClassID = `-- name: FindParticipantsByClassID :many
WITH sort_param AS (
    SELECT COALESCE($2, 'nim')::varchar AS sort_by
)
SELECT
    p.id,
    p.nim,
    p.name,
    p.class_id,
    p.created_at,
    p.updated_at,
    tp.team_id,
    t.number AS team_number
FROM participants p
LEFT JOIN team_participants tp ON tp.participant_id = p.id
LEFT JOIN teams t ON tp.team_id = t.id
CROSS JOIN sort_param sp
WHERE p.class_id = $1
ORDER BY
    CASE WHEN sp.sort_by = 'nim' THEN p.nim END NULLS LAST,
    CASE WHEN sp.sort_by = 'team' THEN team_number END NULLS LAST
`

type FindParticipantsByClassIDParams struct {
	ClassID pgtype.Int4
	SortBy  pgtype.Text
}

type FindParticipantsByClassIDRow struct {
	ID         string
	Nim        string
	Name       string
	ClassID    pgtype.Int4
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	TeamID     pgtype.Text
	TeamNumber pgtype.Int2
}

func (q *Queries) FindParticipantsByClassID(ctx context.Context, arg FindParticipantsByClassIDParams) ([]FindParticipantsByClassIDRow, error) {
	rows, err := q.db.Query(ctx, findParticipantsByClassID, arg.ClassID, arg.SortBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindParticipantsByClassIDRow
	for rows.Next() {
		var i FindParticipantsByClassIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Nim,
			&i.Name,
			&i.ClassID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamID,
			&i.TeamNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findParticipantsByTeamID = `-- name: FindParticipantsByTeamID :many
SELECT
    p.id,
    p.nim,
    p.name,
    p.class_id,
    p.created_at,
    p.updated_at,
    tp.team_id,
    t.number AS team_number
FROM participants p
LEFT JOIN team_participants tp ON tp.participant_id = p.id
LEFT JOIN teams t ON tp.team_id = t.id
WHERE p.class_id = $1
ORDER BY p.nim
`

type FindParticipantsByTeamIDRow struct {
	ID         string
	Nim        string
	Name       string
	ClassID    pgtype.Int4
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	TeamID     pgtype.Text
	TeamNumber pgtype.Int2
}

func (q *Queries) FindParticipantsByTeamID(ctx context.Context, classID pgtype.Int4) ([]FindParticipantsByTeamIDRow, error) {
	rows, err := q.db.Query(ctx, findParticipantsByTeamID, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindParticipantsByTeamIDRow
	for rows.Next() {
		var i FindParticipantsByTeamIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Nim,
			&i.Name,
			&i.ClassID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamID,
			&i.TeamNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertParticipant = `-- name: InsertParticipant :exec
INSERT INTO participants (id, nim, name, class_id)
VALUES ($1, $2, $3, $4)
`

type InsertParticipantParams struct {
	ID      string
	Nim     string
	Name    string
	ClassID pgtype.Int4
}

func (q *Queries) InsertParticipant(ctx context.Context, arg InsertParticipantParams) error {
	_, err := q.db.Exec(ctx, insertParticipant,
		arg.ID,
		arg.Nim,
		arg.Name,
		arg.ClassID,
	)
	return err
}

const resetParticipantTeam = `-- name: ResetParticipantTeam :exec
DELETE FROM team_participants
WHERE
    team_id = $1 AND
    participant_id = $2
`

type ResetParticipantTeamParams struct {
	TeamID        string
	ParticipantID string
}

func (q *Queries) ResetParticipantTeam(ctx context.Context, arg ResetParticipantTeamParams) error {
	_, err := q.db.Exec(ctx, resetParticipantTeam, arg.TeamID, arg.ParticipantID)
	return err
}

const setParticipantTeam = `-- name: SetParticipantTeam :exec
INSERT INTO team_participants (team_id, participant_id)
VALUES ($1, $2)
`

type SetParticipantTeamParams struct {
	TeamID        string
	ParticipantID string
}

func (q *Queries) SetParticipantTeam(ctx context.Context, arg SetParticipantTeamParams) error {
	_, err := q.db.Exec(ctx, setParticipantTeam, arg.TeamID, arg.ParticipantID)
	return err
}
