// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: team.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams
WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const findTeamsByClassID = `-- name: FindTeamsByClassID :many
SELECT
    t.id,
    t.number,
    t.class_id,
    c.name AS class_name,
    c.course_id,
    rc.name AS course_name,
    rc.year AS course_year,
    t.created_at,
    t.updated_at
FROM teams t
INNER JOIN classes c ON t.class_id = c.id
INNER JOIN repl_courses rc ON c.course_id = rc.id
WHERE t.class_id = $1
ORDER BY t.number
`

type FindTeamsByClassIDRow struct {
	ID         string
	Number     int16
	ClassID    pgtype.Int4
	ClassName  string
	CourseID   pgtype.Int4
	CourseName string
	CourseYear int32
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

func (q *Queries) FindTeamsByClassID(ctx context.Context, classID pgtype.Int4) ([]FindTeamsByClassIDRow, error) {
	rows, err := q.db.Query(ctx, findTeamsByClassID, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindTeamsByClassIDRow
	for rows.Next() {
		var i FindTeamsByClassIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.ClassID,
			&i.ClassName,
			&i.CourseID,
			&i.CourseName,
			&i.CourseYear,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTeamsByCourseID = `-- name: FindTeamsByCourseID :many
SELECT
    t.id,
    t.number,
    t.class_id,
    c.name AS class_name,
    c.course_id,
    rc.name AS course_name,
    rc.year AS course_year,
    t.created_at,
    t.updated_at
FROM teams t
INNER JOIN classes c ON t.class_id = c.id
INNER JOIN repl_courses rc ON c.course_id = rc.id
WHERE c.course_id = $1
ORDER BY c.name, t.number
`

type FindTeamsByCourseIDRow struct {
	ID         string
	Number     int16
	ClassID    pgtype.Int4
	ClassName  string
	CourseID   pgtype.Int4
	CourseName string
	CourseYear int32
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

func (q *Queries) FindTeamsByCourseID(ctx context.Context, courseID pgtype.Int4) ([]FindTeamsByCourseIDRow, error) {
	rows, err := q.db.Query(ctx, findTeamsByCourseID, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindTeamsByCourseIDRow
	for rows.Next() {
		var i FindTeamsByCourseIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.ClassID,
			&i.ClassName,
			&i.CourseID,
			&i.CourseName,
			&i.CourseYear,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTeam = `-- name: InsertTeam :exec
INSERT INTO teams (id, number, class_id)
VALUES ($1, $2, $3)
`

type InsertTeamParams struct {
	ID      string
	Number  int16
	ClassID pgtype.Int4
}

func (q *Queries) InsertTeam(ctx context.Context, arg InsertTeamParams) error {
	_, err := q.db.Exec(ctx, insertTeam, arg.ID, arg.Number, arg.ClassID)
	return err
}

const updateTeamNumber = `-- name: UpdateTeamNumber :exec
UPDATE teams
SET
    number = $1,
    updated_at = $2
WHERE id = $3
`

type UpdateTeamNumberParams struct {
	Number    int16
	UpdatedAt pgtype.Timestamp
	ID        string
}

func (q *Queries) UpdateTeamNumber(ctx context.Context, arg UpdateTeamNumberParams) error {
	_, err := q.db.Exec(ctx, updateTeamNumber, arg.Number, arg.UpdatedAt, arg.ID)
	return err
}
